---
sudo: false
language: ruby
bundler_args: --without development integration
script: "bundle exec rake validate lint spec SPEC_OPTS='--color --format documentation'"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
  - rvm: 2.1.10
    env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
  - rvm: 2.1.10
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.2.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.3.3
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.4.0
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  allow_failures:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
    - rvm: 2.1.10
      env: PUPPET_GEM_VERSION="~> 3.0" STRICT_VARIABLES="yes" FUTURE_PARSER="yes"
